### ISSUE TITLE
Native library import does not support linux3

### ISSUE THREAD

**Issue by red-hara** [perey/pegl#1]
Shouldn't line 46 in native.py be set to
`if sys.platform == 'linux':` or `if sys.platfom == 'linux2' or sys.platform == 'linux3'`?
That should enable usage of pegl on modern kernels.
Or, maybe, there is no support for 3rd kernel?
Thank you in advance.

**Comment by perey** [comment]
The [Linux platform test](https://github.com/perey/pegl/blob/develop/src/pegl/native.py#L47) is currently `if sys.platform.startswith('linux'):`, which should work correctly regardless of whether Python reports the platform as `linux`, `linux2` or `linux3`.

If it's not working for you, please let me know what error message you get, and if possible, what result running the following code gives you:

```
import sys
print(sys.platform)
```

Thank you!

**Comment by red-hara** [comment]
`import pegl`
`pegl.__version__`
`'0.1a3~1.4'`
`import sys`
`print(sys.version)`
`3.5.1 (default, Mar  3 2016, 09:29:07)`
`[GCC 5.3.0]`
I suppose I was using an old version, distributed via pip. I'll download newer version and will inform you at once.

**Comment by perey** [comment]
Ahh, yes. It makes sense now. Sorry, there hasn't been a new release on PyPI for a while.

**Comment by red-hara** [comment]
Thank you, this part is working properly.
Issue closed.
