### ISSUE TITLE
pegl doesn't provide the OpenGL API

### ISSUE THREAD

**Issue by wiz21b** [perey/pegl#17]
(First of all, I must tell I don't understand much about EGL)

So I want to make some OpenGL (computing with shaders) on a headless server. I already have the OpenGL code and it works fine inside PyGame and wxPython. I wanted to "port" it to EGL as I understand this is the only way to make it run without an actual window. I downloaded your code, took the ANGLE dll (libEGL.dll, libGLESv2.dll) in the egl/lib directory and ran your code. It works fine apparently until the point where I want to actually run some OpenGL commands. So here's the program (I've taken part from yours) :

```
from OpenGL.GL import glClear, GL_COLOR_BUFFER_BIT
import pegl

import pegl, platform
print('Python', platform.python_version(), 'on', platform.platform(terse=True))
dpy = pegl.Display()
print('EGL version:', dpy.version_string, 'by', dpy.vendor)
all_configs = dpy.get_configs()
print('Configs available:', len(all_configs))
if len(all_configs) > 0:
    cfg = all_configs[0]
    print('The first config...')
    print('\tAPIs supported:', cfg.renderable_type)
    print(f'\tColor buffer: {cfg.buffer_size}-bit', cfg.color_buffer_type.name)
else:
    print('What kind of EGL implementation offers no configurations, anyway?!')


conf = dpy.choose_config({pegl.ConfigAttrib.RENDERABLE_TYPE:
                            pegl.ClientAPIFlag.OPENGL_ES})[0]
pegl.bind_api(pegl.ClientAPI.OPENGL_ES)
ctx = conf.create_context()
print(ctx)
surf = conf.create_pbuffer_surface({pegl.SurfaceAttrib.WIDTH: 640,
                                    pegl.SurfaceAttrib.HEIGHT: 480})
print(surf)
print(ctx.make_current(draw=surf))
glClear(GL_COLOR_BUFFER_BIT)
```

And here is it the output:

```
Python 3.9.13 on Windows-10
EGL version: 1.5 (ANGLE 2.1.19724 git hash: ceec659ac60b) by Google Inc. (NVIDIA)
Configs available: 200
The first config...
        APIs supported: ClientAPIFlag.OPENGL_ES3|OPENGL_ES2|OPENGL_ES
        Color buffer: 16-bit RGB
Google Inc. (NVIDIA)
(1, 5, '(ANGLE 2.1.19724 git hash: ceec659ac60b)')
<pegl.context.Context object at 0x000001D939DD67F0>
<pegl.surface.Surface object at 0x000001D93A60F520>
None
Traceback (most recent call last):
  File "d:\newgit\HECEPython\debug\test_glsim\test_pegl.py", line 31, in <module>
    glClear(GL_COLOR_BUFFER_BIT)
  File "C:\Users\StephaneC\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\Users\StephaneC\AppData\Local\Programs\Python\Python39\lib\site-packages\OpenGL\error.py", 
line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'op\xe9ration non valide',
        baseOperation = glClear,
        cArguments = (GL_COLOR_BUFFER_BIT,)
)
```

The first obvious point is that it crashes on a simple OpenGL code. Did I miss something ? The second point is that the reported supported API's don't include regular OpenGL. That's surprising. Just to be on the safe side I also included opengl32.dll in the egl/lib directory but to no avail...

So it doesn't work but I'm not sure it is on the pegl side or mine :-(  So if you ever have some interest in this issue, I'd be happy to hear it :-)

**Comment by perey** [comment]
Thanks for the report! No, Pegl doesn’t provide the OpenGL API.

*In theory*, it should be possible to use Pegl together with PyOpenGL, as you’re trying to do. *In practice*, it will not. You should instead see if PyOpenGL itself provides what you need. (It does seem like PyOpenGL’s own WGL module [has support for pbuffers](https://pyopengl.sourceforge.net/documentation/pydoc/OpenGL.WGL.ARB.pbuffer.html), which are off-screen rendering surfaces, so this may be a good sign for your headless server use case.)

---

A bit of background on EGL (and please understand I’m not an expert, just a hobbyist): OpenGL has been around a long time, and different platforms supplemented it with their own support libraries. X11 had GLX, Apple had CGL, Microsoft had WGL… there may have been others, but those are the three I know of. They provided (and still provide) things that weren’t part of OpenGL itself, like managing rendering surfaces (on-screen or off-screen).

Then along came OpenGL ES, a slimmed-down version of OpenGL designed for embedded systems first and foremost. EGL emerged at the same time, and was presumably intended to go with it: a standardised alternative to those other platform libraries, one that embedded platforms could provide.

OpenGL ES has been very successful, particularly thanks to the uptake of mobile computing, and quite a bit of software now targets it even on the desktop (e.g. Google Chrome). Presumably it’s easier to just write everything for one graphics API.

EGL has not been so successful. It *is* used alongside OpenGL ES on mobile platforms, and on desktop it’s a core part of the Wayland platform, but Khronos evidently wanted it to go further. The specification *allows* EGL to be used together with other APIs, namely regular OpenGL, and the (also sadly unsuccessful) OpenVG vector graphics API. But that doesn’t mean that any particular implementation of EGL will actually *use* those APIs.

Pegl is not an EGL implementation—it just lets Python access an implementation. When you get the DLLs from your Chrome installation, you’re getting Google’s EGL implementation, and they chose to only support OpenGL ES.

At some time in the future, I’d like to see whether it’s possible to get Pegl and PyOpenGL to work together. (It should be possible. They have their own [EGL wrapper](https://pyopengl.sourceforge.net/documentation/pydoc/OpenGL.platform.egl.html), so it ought to be possible to use another EGL wrapper instead.) But this will only work on platforms that have EGL and OpenGL implementations that are already made for working together.

**Comment by perey** [comment]
[ModernGL](https://github.com/moderngl/moderngl) is a Python binding to OpenGL that says that it supports headless rendering, so I’d suggest you look at that for your needs. Sorry I couldn’t be more helpful!

Closing as out of scope for Pegl.
