### ISSUE TITLE
Pegl has no attribute display

### ISSUE THREAD

**Issue by henzler** [perey/pegl#2]
After installing pegl via:

`pip install pegl`

I get following error when trying to create the egl context:

```
import pegl
from pegl.attribs.config import ClientAPIs, CBufferTypes
from pegl.attribs.context import ContextAPIs
dpy = pegl.display.Display()
```

> AttributeError: module 'pegl' has no attribute 'display'

**Comment by henzler** [comment]
So I have figured out that there is no folder for display (anymore, or never has been?) therefore one has to use: 
from pegl import display
dpy = display.Display()

However, then one retrieves:

> raise ImportError('Pegl not supported on {}'.format(sys.platform))
> ImportError: Pegl not supported on linux


```
# Native library import.
libname = 'libEGL'
if sys.platform == 'linux2':
    libclass, libext = ctypes.CDLL, '.so'
elif sys.platform == 'darwin':
    libclass, libext = ctypes.CDLL, '.dylib'
elif sys.platform == 'win32':
    libclass, libext = ctypes.WinDLL, '.dll'
else:
    raise ImportError('Pegl not supported on {}'.format(sys.platform))
```
After replacing 'linux2' with 'linux' the code is working

**Comment by perey** [comment]
Thanks for reporting this, and I apologise for it taking so long (two years!) to get a reply. My original use case for this code fell through, so it's sat unused for a long time. The issues you reported were with the version available on PyPI, and they (or at least the second one) were corrected in development code that was never shipped.

As it is, I'm working on this code again now, and the imports have changed, so I'm closing this issue. Thanks again for reporting it!
