### ISSUE TITLE
pegl version format

### ISSUE THREAD

**Issue by rayzchen** [perey/pegl#4]
Currently with the format `w.x_y.z` pip does not recognise the version format. Running `pip install pegl` gives `ERROR: Could not find a version that satisfies the requirement pegl (from versions: 0.1a3~1.4, 0.1a4_1.4)` whereas downloading the sdist gives `WARNING: Built wheel for pegl is invalid: Metadata 1.2 mandates PEP 440 version, but '0.1a4-1.4' is not`. It does install, however it uses the outdated `python setup.py install` mechanism. Using a PEP 440 version string could fix this, however I don't see how you would be able to include both the wrapped EGL version and the python PEGL version in one version string.

**Comment by perey** [comment]
This will be fixed in the next version, which will no longer include the EGL version number in the PEGL version string.

The upcoming version is in the [`refresh`](https://github.com/perey/pegl/tree/refresh) branch, and is just awaiting testing and bugfixes before release.

**Comment by rayzchen** [comment]
Glad to see this being actively maintained! I'd gladly help you if you need me to. On a side note, is this supported on Windows?

**Comment by perey** [comment]
“Actively” maintained might be a stretch, but yeah, I work on it occasionally. 🙂

And as it happens, it presently works *better* on Windows with ANGLE than it does on Linux with Mesa.

**Comment by rayzchen** [comment]
On a side note, the example in `README.rst` gives `AttributeError: 'Config' object has no attribute 'get_context'`. (from `refresh` branch)

**Comment by perey** [comment]
Version 0.2a1 is now available from PyPI.

> On a side note, the example in `README.rst` gives `AttributeError: 'Config' object has no attribute 'get_context'`. (from `refresh` branch)

Thanks for pointing that out. It should've been `create_context`. This is fixed in 5011d6a, part of the new release.
